---

- include_vars: "{{ role_path }}/vars/templates.yml"

- name: customize job templates
  awx.awx.tower_job_template:
    tower_host: "https://{{ ansible_host }}"
    tower_username: admin
    tower_password: "{{ tower_setup_admin_password }}"
    validate_certs: no
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    job_type: "{{ item.job_type | default(omit) }}"
    inventory: "{{ item.inventory | default(omit) }}"
    project: "{{ item.project | default(omit) }}"
    playbook: "{{ item.playbook | default(omit) }}"
    credential: "{{ item.credential | default(omit) }}"
    credentials: "{{ item.credentials | default(omit) }}"
    job_tags: "{{ item.job_tags | default(omit) }}"
    skip_tags: "{{ item.skip_tags | default(omit) }}"
    verbosity: "{{ item.verbosity | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    survey_spec: "{{ item.survey_spec | default(omit) }}"
    survey_enabled: "{{ item.survey_enabled | default(omit) }}"
    extra_vars: "{{ item.extra_vars | default(omit) }}"
  loop: "{{ __tower_job_template }}"
  register: _template_result 
  until: _template_result is not failed
  delay: 5
  retries: 12
  loop_control:
    label: "{{ item.name }}"

- name: job template results
  debug: 
    var: _template_result
    verbosity: 2
  