---

- include_vars: "{{ role_path }}/vars/projects.yml"

- name: "install GitHub projects"
  tower_project: 
    tower_host: "https://{{ ansible_host }}"
    tower_username: admin
    tower_password: "{{ tower_setup_admin_password }}"
    validate_certs: no
    organization: Default
    name: "{{ item.name }}"
    scm_type: git
    description: "{{ item.description | default(omit) }}"
    scm_clean: "{{ item.clean | default(omit) }}"
    scm_url: "{{ item.scm_url | default(omit) }}"
  loop: "{{ __tower_projects }}"
  loop_control:
    label: "{{ item.name }}"
